// src/components/tropess/ProductCatalogSection.js
// TROPESS "Published Data Products" section (slides 1 & 2 of the GES DISC deck).
//
// Data comes from public/data/TROPESS_catalog.json, generated by
// scripts/build_tropess_catalog.py from NASA's CMR (the live product catalog
// behind disc.gsfc.nasa.gov).

import React, { useEffect, useMemo, useState } from 'react';
import {
  PieChart, Pie, Cell, BarChart, Bar, XAxis, YAxis, CartesianGrid,
  Tooltip, ResponsiveContainer,
} from 'recharts';
import { Boxes, Database, Clock, ExternalLink, Cloud } from 'lucide-react';

const CATALOG_URL = 'https://disc.gsfc.nasa.gov/datasets?keywords=tropess';

const LEVEL_COLORS = { 'L2 (satellite)': '#3B82F6', 'L4 (assimilation)': '#10B981' };
const STREAM_COLORS = {
  Forward: '#3B82F6', Reanalysis: '#10B981', Megacity: '#F59E0B', Special: '#EC4899',
};
const CATEGORICAL = [
  '#3B82F6', '#10B981', '#F59E0B', '#EC4899', '#8B5CF6', '#06B6D4', '#F97316', '#84CC16',
];

// --- Card shell (matches MonthlyReportSection) -----------------------------
const Card = ({ title, subtitle, icon, children, className = '' }) => (
  <div className={`bg-white rounded-lg p-5 shadow-sm ${className}`}>
    <div className="mb-4">
      <div className="flex items-center gap-2 text-lg font-semibold text-gray-800">
        {icon}
        {title}
      </div>
      {subtitle && <p className="text-sm text-gray-500 mt-1">{subtitle}</p>}
    </div>
    {children}
  </div>
);

const yearFrac = (iso) => {
  if (!iso) return null;
  const d = new Date(iso);
  return d.getUTCFullYear() + d.getUTCMonth() / 12;
};

// Slide 2 timeline: one row per instrument, bar spans earliest→latest coverage.
const ScopeTimeline = ({ products }) => {
  const { rows, minYear, maxYear } = useMemo(() => {
    const groups = {};
    products.forEach((p) => {
      const s = yearFrac(p.start);
      if (s == null) return;
      const e = p.ongoing || !p.end ? null : yearFrac(p.end);
      const g = groups[p.instrument] || (groups[p.instrument] = {
        instrument: p.instrument, min: s, max: e ?? s, ongoing: false, count: 0,
      });
      g.min = Math.min(g.min, s);
      g.max = Math.max(g.max, e ?? s);
      if (p.ongoing || !p.end) g.ongoing = true;
      g.count += 1;
    });
    const rows = Object.values(groups).sort((a, b) => a.min - b.min);
    const nowY = new Date().getUTCFullYear() + new Date().getUTCMonth() / 12;
    const allMin = Math.floor(Math.min(...rows.map((r) => r.min)));
    const allMax = Math.ceil(Math.max(nowY, ...rows.map((r) => r.max)));
    rows.forEach((r) => { if (r.ongoing) r.max = nowY; });
    return { rows, minYear: allMin, maxYear: allMax };
  }, [products]);

  if (!rows.length) return null;

  const span = maxYear - minYear || 1;
  const pct = (y) => ((y - minYear) / span) * 100;
  const ticks = [];
  for (let y = minYear; y <= maxYear; y += Math.ceil(span / 8) || 1) ticks.push(y);

  return (
    <div className="w-full">
      {/* Year axis */}
      <div className="relative h-5 ml-40 mr-2 mb-1">
        {ticks.map((y) => (
          <span key={y} className="absolute text-xs text-gray-400 -translate-x-1/2"
            style={{ left: `${pct(y)}%` }}>{y}</span>
        ))}
      </div>
      {rows.map((r, i) => (
        <div key={r.instrument} className="flex items-center h-9">
          <div className="w-40 pr-3 text-xs text-gray-700 text-right truncate" title={r.instrument}>
            {r.instrument}
          </div>
          <div className="relative flex-1 h-5 bg-gray-50 rounded">
            <div
              className="absolute h-5 rounded flex items-center"
              style={{
                left: `${pct(r.min)}%`,
                width: `${Math.max(pct(r.max) - pct(r.min), 1.5)}%`,
                backgroundColor: CATEGORICAL[i % CATEGORICAL.length],
              }}
              title={`${r.instrument}: ${r.min.toFixed(0)}–${r.ongoing ? 'present' : r.max.toFixed(0)} (${r.count} products)`}
            >
              {r.ongoing && (
                <span className="absolute -right-1 top-1/2 -translate-y-1/2 w-2 h-2 rounded-full bg-white border border-gray-400" />
              )}
            </div>
          </div>
        </div>
      ))}
      <div className="ml-40 mt-2 text-xs text-gray-400">
        Bars show data-coverage range per instrument; ○ = ongoing (updated to present).
      </div>
    </div>
  );
};

const ProductCatalogSection = () => {
  const [catalog, setCatalog] = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    fetch(`${process.env.PUBLIC_URL}/data/TROPESS_catalog.json`)
      .then((r) => { if (!r.ok) throw new Error(`HTTP ${r.status}`); return r.json(); })
      .then(setCatalog)
      .catch((e) => { console.error('Failed to load TROPESS catalog:', e); setError(e.message); });
  }, []);

  if (error) {
    return (
      <div className="bg-white rounded-lg p-5 shadow-sm mb-6">
        <div className="text-lg font-semibold text-gray-800 mb-2">Published Data Products</div>
        <p className="text-sm text-red-600">
          Unable to load product catalog ({error}). Run{' '}
          <code>python scripts/build_tropess_catalog.py</code> to generate the data.
        </p>
      </div>
    );
  }
  if (!catalog) {
    return (
      <div className="bg-white rounded-lg p-5 shadow-sm mb-6">
        <div className="text-lg font-semibold text-gray-800 mb-2">Published Data Products</div>
        <p className="text-sm text-gray-500">Loading product catalog…</p>
      </div>
    );
  }

  const { summary, products } = catalog;

  return (
    <section className="mb-6">
      {/* Section header + slide 1 stat tiles */}
      <div className="bg-white rounded-lg p-6 shadow-sm mb-6 border-t-4 border-cyan-600">
        <div className="flex items-start justify-between gap-3">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-cyan-50 rounded-lg">
              <Boxes size={24} className="text-cyan-600" />
            </div>
            <div>
              <h2 className="text-2xl font-bold text-gray-900">Published Data Products</h2>
              <p className="text-gray-500 text-sm mt-1">
                Live TROPESS product catalog from NASA GES DISC (via CMR)
              </p>
            </div>
          </div>
          <a href={CATALOG_URL} target="_blank" rel="noopener noreferrer"
            className="inline-flex items-center gap-1 text-sm text-cyan-700 hover:text-cyan-900 whitespace-nowrap">
            GES DISC <ExternalLink size={14} />
          </a>
        </div>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mt-5">
          <div>
            <div className="text-2xl font-bold text-gray-900">{summary.total_products}</div>
            <div className="text-xs text-gray-500">Data products (unique DOI)</div>
          </div>
          <div>
            <div className="text-2xl font-bold text-gray-900">{summary.by_level.length}</div>
            <div className="text-xs text-gray-500">Processing levels</div>
          </div>
          <div>
            <div className="text-2xl font-bold text-gray-900">{summary.by_instrument.length}</div>
            <div className="text-xs text-gray-500">Instrument sources</div>
          </div>
          <div>
            <div className="flex items-center gap-1 text-2xl font-bold text-gray-900">
              <Cloud size={22} className="text-cyan-600" /> Yes
            </div>
            <div className="text-xs text-gray-500">Publicly cloud-enabled</div>
          </div>
        </div>
        {summary.est_total_volume_tb != null && (
          <div className="mt-3 text-xs text-gray-400">
            Estimated published volume ≈ {summary.est_total_volume_tb} TB across{' '}
            {summary.est_total_files?.toLocaleString()} files (granules × avg file size).
          </div>
        )}
      </div>

      {/* Slide 1 charts: by level + by instrument */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-6">
        <Card title="Products by Processing Level" icon={<Database size={18} className="text-cyan-600" />}>
          <ResponsiveContainer width="100%" height={280}>
            <PieChart>
              <Pie data={summary.by_level} dataKey="count" nameKey="level" cx="50%" cy="50%"
                outerRadius={100} label={({ level, percent }) => `${level} ${(percent * 100).toFixed(0)}%`}
                labelLine={false}>
                {summary.by_level.map((e) => (
                  <Cell key={e.level} fill={LEVEL_COLORS[e.level] || '#9ca3af'} />
                ))}
              </Pie>
              <Tooltip formatter={(v) => [`${v} products`, 'Count']} />
            </PieChart>
          </ResponsiveContainer>
        </Card>

        <Card title="Products by Instrument" icon={<Boxes size={18} className="text-cyan-600" />}>
          <ResponsiveContainer width="100%" height={280}>
            <BarChart data={summary.by_instrument} layout="vertical"
              margin={{ top: 5, right: 40, left: 10, bottom: 0 }}>
              <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" horizontal={false} />
              <XAxis type="number" tick={{ fontSize: 11 }} />
              <YAxis type="category" dataKey="instrument" tick={{ fontSize: 11 }} width={150} />
              <Tooltip formatter={(v) => [`${v} products`, 'Count']} />
              <Bar dataKey="count" radius={[0, 3, 3, 0]}>
                {summary.by_instrument.map((e, i) => (
                  <Cell key={e.instrument} fill={CATEGORICAL[i % CATEGORICAL.length]} />
                ))}
              </Bar>
            </BarChart>
          </ResponsiveContainer>
        </Card>
      </div>

      {/* Slide 2: scope & range timeline */}
      <Card
        title="Data Products Scope and Range"
        subtitle="Data-coverage time range by instrument / processing type"
        icon={<Clock size={18} className="text-cyan-600" />}
        className="mb-2"
      >
        <ScopeTimeline products={products} />

        {/* Stream legend */}
        <div className="flex flex-wrap gap-x-4 gap-y-1 mt-4 pt-3 border-t border-gray-100 text-xs text-gray-600">
          {summary.by_stream.map((s) => (
            <span key={s.stream} className="inline-flex items-center gap-1">
              <span className="w-3 h-3 rounded-sm" style={{ backgroundColor: STREAM_COLORS[s.stream] || '#9ca3af' }} />
              {s.stream}: {s.count}
            </span>
          ))}
        </div>
      </Card>

      <p className="text-xs text-gray-400 mt-2">
        Source: NASA CMR (cmr.earthdata.nasa.gov), provider GES DISC. Product counts reflect the live catalog.
      </p>
    </section>
  );
};

export default ProductCatalogSection;
